details#120#179
MargaritaBespalova/JobSearchEngine pull request #234
Opened 2023-09-10 17:23 UTC by DanilaYazykov

2023-09-10 18:32 UTC, MargaritaBespalova requested changes

2023-09-10 18:32 UTC, MargaritaBespalova commented on app/src/main/java/ru/practicum/android/diploma/details/data/local/db/FavoriteDao.kt
> +    fun getFavoritesById(id: String): Flow<VacancyFullInfoEntity>
Можно получать сразу булевое значение вот таким запросом:
```
   @Query("SELECT EXISTS(SELECT 1 FROM selected_tracks WHERE id = :id LIMIT 1);")
    fun isFavorite(id: String): Flow<Boolean>
```

2023-09-10 18:32 UTC, MargaritaBespalova commented on app/src/main/java/ru/practicum/android/diploma/details/data/local/model/VacancyConverter.kt
> +    }*/
Не оставляете закомментированный код пожалуйста. Потом забудем удалить лишнее

2023-09-10 18:32 UTC, MargaritaBespalova commented on app/src/main/java/ru/practicum/android/diploma/details/data/local/model/VacancyConverter.kt
> +    private fun toVacancy(vacancyEntity: VacancyFullInfoEntity): Vacancy {
Можно вместо двух методов, перегрузить один типо такого: 
private fun map(data: VacancyFullInfoEntity): Vacancy {}
private fun map(data: Vacancy):  VacancyFullInfoEntity{}

2023-09-10 18:32 UTC, MargaritaBespalova commented on app/src/main/java/ru/practicum/android/diploma/details/data/local/model/VacancyFullInfoEntity.kt
> +    val alternateUrl: String? = ""
Зачем `?` в 25 строке, есть есть дефолтное значение?

2023-09-10 18:32 UTC, MargaritaBespalova commented on app/src/main/java/ru/practicum/android/diploma/details/ui/DetailsFragment.kt
> +  //      viewModel.getFavoriteVacancyById(args.vacancy.id)
убрать закомментированный код

2023-09-10 18:32 UTC, MargaritaBespalova commented on app/src/main/java/ru/practicum/android/diploma/details/ui/DetailsViewModel.kt
> +                _uiState.value = DetailsScreenState.PlayHeartAnimation(vacancy, viewModelScope)
нужно убрать рендеринг из силд класса с состояниями

2023-09-11 07:21 UTC, DanilaYazykov commented on app/src/main/java/ru/practicum/android/diploma/details/data/local/model/VacancyConverter.kt
> +    }*/
Это не конечная версия была)
С Игорем вчера разбирались, для наглядности залил.

2023-09-11 07:23 UTC, DanilaYazykov commented on app/src/main/java/ru/practicum/android/diploma/details/data/local/db/FavoriteDao.kt
> +    fun getFavoritesById(id: String): Flow<VacancyFullInfoEntity>
Крутяк, сейчас затестю)))

2023-09-11 07:54 UTC, MargaritaBespalova approved these changes

2023-09-11 08:00 UTC, merged